"""added foreignkey to products

Revision ID: 0243caa2f362
Revises: e710835d111d
Create Date: 2025-09-09 19:03:45.138869

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0243caa2f362'
down_revision: Union[str, Sequence[str], None] = 'e710835d111d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('review_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'products', 'reviews', ['review_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'products', type_='foreignkey')
    op.drop_column('products', 'review_id')
    # ### end Alembic commands ###
