"""Add user model

Revision ID: 85acaaa59d14
Revises: 3b0e7caaba84
Create Date: 2025-09-07 12:04:56.168741

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '85acaaa59d14'
down_revision: Union[str, Sequence[str], None] = '3b0e7caaba84'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    op.execute("DELETE FROM products")
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
